title: IBM Z® Open Editor
description: The IBM Z® Open Editor is an IBM Enterprise Language Extension for Visual Studio Code
keywords: IBM, COBOL, PL/I, PLI, PL1, JCL, jesjcl, jesmsglg, jesysmsg, IDE, LSP, language-server, keybindings, snippet, z/OS, zOS, Z Software, Zowe, Mainframe, Visual Studio Code, VS Code, VSCode, Git, Open Source, Development, Extension, Theia, Che
baseurl: "/"

# Build settings
theme: minima
exclude: [node_modules]
